name: Build All Packages

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      jose_version:
        description: The jose version we're building
        value: ${{ jobs.build.outputs.jose_version }}
      build_version:
        description: The build date
        value: ${{ jobs.build.outputs.build_version }}

env:
  DOCKER_USER: greycubesgav
  DOCKER_IMAGE_NAME: slackbuild-jose

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      jose_version: ${{ env.JOSE_VERSION }}
      build_version: ${{ steps.version-setter.outputs.build_version }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: get version
        id: version-setter
        run: |
          jose_version=$(awk -F'"' '/^VERSION=/{print $2}' ./src/jose/*.info)
          build_version=$(date +%Y%m%d)
          echo "Building release jose v${jose_version} build ${build_version}"
          echo "jose_version=${jose_version}" >> "$GITHUB_OUTPUT"
          echo "build_version=${build_version}" >> "$GITHUB_OUTPUT"
          echo "JOSE_VERSION=$jose_version" >> $GITHUB_ENV
          echo "BUILD_VERSION=$build_version" >> $GITHUB_ENV
        shell: bash

      - name: build
        run: |
          echo "Building version jose v${{ env.JOSE_VERSION }} build ${{ env.BUILD_VERSION }} for slackware v15.0 and vCurrent"
          make BUILD=${{ env.BUILD_VERSION }} docker-artifact-build-${{ env.JOSE_VERSION }}-current
          make BUILD=${{ env.BUILD_VERSION }} docker-artifact-build-${{ env.JOSE_VERSION }}-15.0
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slackbuild-pkgs
          path: pkgs/*


