name: Build All Packages

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_USER: greycubesgav
  DOCKER_IMAGE_NAME: slackbuild-jose

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: get version
        run: |
          release_version=$(awk -F'"' '/^VERSION=/{print $2}' ./src/jose/*.info)
          echo "Building release version $release_version"
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
        shell: bash

      - name: build
        run: |
          echo "Building version ${{ env.RELEASE_VERSION }}"
          make docker-artifact-build-aclemons-${{ env.RELEASE_VERSION }}-current
          make docker-artifact-build-aclemons-${{ env.RELEASE_VERSION }}-15.0
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slackbuild-pkgs
          path: pkgs/*
