name: Create Release

on:

  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  build:
    uses: ./.github/workflows/build.yml

  create_release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Packages from build step
      uses: actions/download-artifact@v4
      with:
        name: slackbuild-pkgs
        path: pkgs/

    - name: Display structure of downloaded packages
      run: ls -R pkgs/

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.RELEASE_VERSION }}
        name: Release v${{ env.RELEASE_VERSION }}
        draft: true
        files: pkgs/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}